# Generated by Django 4.0.5 on 2022-07-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baza', models.FileField(upload_to='baza savollar')),
                ('description', models.TextField(blank=True, null=True)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fanlar')),
            ],
        ),
    ]
